version: "3"
services:
  redis:
    image: redis:alpine
    networks: 
      - webnet
    restart: always
  db:
    image: postgres:alpine
    volumes:
      - ./pgdata:/var/lib/postgresql
    networks: 
      - webnet
    environment:
      POSTGRES_PASSWORD: skillz21
      POSTGRES_USER: postgres
      POSTGRES_DB: tvshows
    restart: always
  web:
    image: nip10/tvshows-manager:latest
    ports:
      - "3001:3001"
    networks:
      - webnet
    environment:
      DATABASE_HOST_PROD: db
      REDIS_HOST: redis
    depends_on:
      - db
      - redis
    restart: always
    command: ["./wait-for-it.sh", "db:5432", "--", "node", "./dist/server.js"]
networks:
  webnet: